---
title: "Introduction to onhpackage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to onhpackage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The goal of `toypackage` is to provide convenience functions for some common tasks. You can install this package from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
# install.packages("devtools")
devtools::install_github("owennhorton/onhpackage")
```

Load the package using this code:

```{r example}
library(onhpackage)
```

#### strsplit1 example

```{r}
first_subject_words <- toy_data$recalled_words[1]
strsplit1(first_subject_words, split = ", ")
```

#### min_max_scale example

```{r}
min_max_scale(toy_data$test_score)
```

#### theme_academic example

```{r, fig.align='center'}
library(ggplot2)
ggplot(toy_data, aes(x = reaction_time, y = test_score)) +
geom_point(size = 4, color = "steelblue") +
labs(title = "Faster Reaction Times Correlate with Higher Scores",
x = "Reaction Time (seconds)", y = "Scaled Test Score (0 to 1)") +
theme_academic(base_size = 14)
```

```{r setup}
library(onhpackage)
```
